
ADMIN_EMAIL: "ADMIN_EMAIL ADDRESS"

development:
  GMAIL_USERNAME: "YOUR_USERNAME"
  GMAIL_PASSWORD: "YOUR_PASSWORD"

  FACEBOOK_KEY: "YOUR_KEY"
  FACEBOOK_SECRET: "YOUR_SECRET"

  TWITTER_KEY: "YOUR_KEY"
  TWITTER_SECRET: "YOUR_SECRET"

  GOOGLE_KEY: "YOUR_KEY"
  GOOGLE_SECRET: "YOUR_SECRET"

test:
  GMAIL_USERNAME: "YOUR_USERNAME"
  GMAIL_PASSWORD: "YOUR_PASSWORD"

  FACEBOOK_KEY: "YOUR_KEY"
  FACEBOOK_SECRET: "YOUR_SECRET"

  TWITTER_KEY: "YOUR_KEY"
  TWITTER_SECRET: "YOUR_SECRET"

  GOOGLE_KEY: "YOUR_KEY"
  GOOGLE_SECRET: "YOUR_SECRET"

production:
  GMAIL_USERNAME: "YOUR_USERNAME"
  GMAIL_PASSWORD: "YOUR_PASSWORD"

  FACEBOOK_KEY: "YOUR_KEY"
  FACEBOOK_SECRET: "YOUR_SECRET"

  TWITTER_KEY: "YOUR_KEY"
  TWITTER_SECRET: "YOUR_SECRET"

  GOOGLE_KEY: "YOUR_KEY"
  GOOGLE_SECRET: "YOUR_SECRET"    